<a href="https://colab.research.google.com/github/jgarc826/Project1/blob/main/Cs105FinalProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CS105 Final Project

By:

Ihsan Sarwar
isarw001@ucr.edu

Mostafa Elmallah
melma006@ucr.edu

Muhammad Abid
mabid002@ucr.edu

Muhammad Sabeel
msabe004@ucr.edu

Jessy Garcia
jgarc826@ucr.edu



---

In [1]:
import os

cwd = os.getcwd()
print(cwd)

/content

In [2]:
import pandas as pd
from google.colab import files

# Suppose the file is named 'data.csv'
df = pd.read_csv('ClimateData2022_2025.csv')

# Check the first few rows
df.head()

,date,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun
0,2022-01-01 00:00:00,11.3,8.3,16.1,0.0,NaN,NaN,1.6,NaN,1019.0,NaN
1,2022-01-02 00:00:00,11.0,6.7,17.8,0.0,NaN,NaN,3.0,NaN,1023.9,NaN
2,2022-01-03 00:00:00,10.7,6.1,16.1,0.0,NaN,NaN,2.3,NaN,1022.5,NaN
3,2022-01-04 00:00:00,10.4,6.1,16.7,0.0,NaN,NaN,0.3,NaN,1022.8,NaN
4,2022-01-05 00:00:00,12.3,6.7,19.4,0.0,NaN,NaN,0.5,NaN,1018.0,NaN

**Data Cleaning**

Step 1: Change the Variable Names to more readable names

Step 2: Convert the temperatures to Farenheight as they are in Celcuis.

Step 3: We found that the Riverside dataset is missing values for wind direction, peak wind gust speed, and sunshine duration. Because these variables use 0 as a meaningful value, we cannot safely replace the missing values with zero. Instead of introducing inaccurate or misleading data, we will remove these variables entirely from the dataset and proceed only with the features that have complete and reliable observations. However, for snow, we may fill in with the value 0 since it does not snow in Riverside.(Need to ask for opinion from TA or Professor; for now it is dropped.)

Step 4: We will be dropping any observations that only have the "Date' but are missing every other single column value.

Note: It may be worth finding a dataset that has the values of time of sun/wind direction/ peak wind gust speed

In [3]:

#Data Cleaning: Step 1
df.columns = ['Date','avgTemp', 'minTemp', 'maxTemp', 'precipitation', 'snow','windDirection', 'windSpd', 'wpgt', 'AirPressure', 'tsun']
df.head()

,Date,avgTemp,minTemp,maxTemp,precipitation,snow,windDirection,windSpd,wpgt,AirPressure,tsun
0,2022-01-01 00:00:00,11.3,8.3,16.1,0.0,NaN,NaN,1.6,NaN,1019.0,NaN
1,2022-01-02 00:00:00,11.0,6.7,17.8,0.0,NaN,NaN,3.0,NaN,1023.9,NaN
2,2022-01-03 00:00:00,10.7,6.1,16.1,0.0,NaN,NaN,2.3,NaN,1022.5,NaN
3,2022-01-04 00:00:00,10.4,6.1,16.7,0.0,NaN,NaN,0.3,NaN,1022.8,NaN
4,2022-01-05 00:00:00,12.3,6.7,19.4,0.0,NaN,NaN,0.5,NaN,1018.0,NaN

In [4]:
#Data Cleaning: Step 2
df['avgTemp'] = df['avgTemp'] * 9/5 + 32
df['minTemp'] = df['minTemp'] * 9/5 + 32
df['maxTemp'] = df['maxTemp'] * 9/5 + 32

In [5]:
#Data Cleaning: Step 3
df = df.drop(columns=['snow','windDirection', 'wpgt', 'tsun'])

In [6]:
#Quick view at our dataset to ensure everything looks right
df.head()

,Date,avgTemp,minTemp,maxTemp,precipitation,windSpd,AirPressure
0,2022-01-01 00:00:00,52.34,46.94,60.98,0.0,1.6,1019.0
1,2022-01-02 00:00:00,51.80,44.06,64.04,0.0,3.0,1023.9
2,2022-01-03 00:00:00,51.26,42.98,60.98,0.0,2.3,1022.5
3,2022-01-04 00:00:00,50.72,42.98,62.06,0.0,0.3,1022.8
4,2022-01-05 00:00:00,54.14,44.06,66.92,0.0,0.5,1018.0

In [7]:
df.isna().sum()

Date              0
avgTemp          28
minTemp          29
maxTemp          29
precipitation    89
windSpd          28
AirPressure      28
dtype: int64

**Note**: Since each column has some missing variables, we must discuss what to do with each variable and how to fill in its missing value.

In [10]:
#Data Cleaning: Step 4
#While inspecting the dataset, I found that some observations near the bottom contained only the date, with all other weather variables missing.
#This happened because the dataset is dynamic and updates continuously, so future dates may be listed before their measurements are recorded.
#To remove these incomplete observations, I dropped any rows where all non-date columns were missing:
df = df.dropna(subset=df.columns.drop('Date'), how='all')

In [11]:
df

,Date,avgTemp,minTemp,maxTemp,precipitation,windSpd,AirPressure
0,2022-01-01 00:00:00,52.34,46.94,60.98,0.0,1.6,1019.0
1,2022-01-02 00:00:00,51.80,44.06,64.04,0.0,3.0,1023.9
2,2022-01-03 00:00:00,51.26,42.98,60.98,0.0,2.3,1022.5
3,2022-01-04 00:00:00,50.72,42.98,62.06,0.0,0.3,1022.8
4,2022-01-05 00:00:00,54.14,44.06,66.92,0.0,0.5,1018.0
...,...,...,...,...,...,...,...
1416,2025-11-17 00:00:00,57.38,51.98,64.22,16.8,10.2,1013.1
1417,2025-11-18 00:00:00,53.42,48.74,60.26,0.3,6.5,1013.5
1418,2025-11-19 00:00:00,52.34,44.96,60.80,0.0,6.8,1017.1
1419,2025-11-20 00:00:00,51.44,46.04,57.20,15.6,9.2,1015.7
1420,2025-11-21 00:00:00,56.12,NaN,NaN,NaN,11.2,1013.2